[package]
name = "asp-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true
publish = false

[[bin]]
name = "aspd"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
asp-protocol = { path = "../asp-protocol", version = "0.1.0" }
asp-pty = { path = "../asp-pty", version = "0.1.0" }
bytes.workspace = true
clap.workspace = true
crc32fast.workspace = true
fs2.workspace = true
libc.workspace = true
notify.workspace = true
quinn.workspace = true
rcgen.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
subtle.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
